color: lime
fieldLayouts:
  b2844bf4-c6e0-4c3f-857a-dad7dc044ac7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-21T05:28:44+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Label
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6ddb9387-1b07-47d5-87c9-7a0f5a51c5d8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-21T05:32:00+00:00'
            elementCondition: null
            fieldUid: d4f0917b-edcf-4ef0-a98b-661ff27384ad # Page
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c2c2049-ae12-4eda-babe-93d4ef8ea20d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b3d63281-ae65-4c2e-ba4e-3e118c690861
        userCondition: null
handle: pageLink
hasTitleField: true
icon: link
name: 'Page link'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
