color: null
fieldLayouts:
  c89336c4-080e-4733-8042-a2fe82bb0884:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-20T08:30:03+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7c51ef0b-1873-4da0-94e8-a59e7dbd0343
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-20T09:36:26+00:00'
            elementCondition: null
            fieldUid: 6c9778b8-507c-4108-937d-6ceeabf35047 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: 'Hero image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: afc63364-6f55-4d6f-99e4-b6bae3ba3f57
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-20T09:36:26+00:00'
            elementCondition: null
            fieldUid: 6d2e5577-5ded-43c9-96e2-d4fc4c770fe9 # Text
            handle: heading
            includeInCards: false
            instructions: null
            label: Heading
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 38827e8e-7293-47ac-a3ff-14c61c3ce83a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-20T09:36:26+00:00'
            elementCondition: null
            fieldUid: 0a58e287-e038-4eb7-ab2a-cf4cbdbe013d # Page content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e8c92b0c-8394-4f6e-b2ab-19c12217ced3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c2ab8c02-117e-4db0-924c-3e3ba5dae762
        userCondition: null
handle: page
hasTitleField: true
icon: file
name: Page
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
