columnSuffix: null
handle: richText
instructions: null
name: 'Rich text'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: b579b454-12bd-4710-a436-c26907141957 # Full
  createButtonLabel: 'New block'
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
