dateModified: 1723615591
email:
  fromEmail: travis@pixelandtonic.com
  fromName: 'Starter starter'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    6d0d3aa4-84be-441d-8fcc-2ab2d6db2503: 'Starter starter' # Starter starter
    58ccb571-6c72-449f-8e7b-6f43c5d416b3: 'Starter starter' # Starter starter
system:
  edition: solo
  live: true
  name: 'Starter starter'
  schemaVersion: 5.3.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
